<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class CarModels extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    { 
        $renault=array(
                       array('model_name'=>'100','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'200','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'240sx','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'280','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'300','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'350z','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'370z','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'almera','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'altima','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'bluebird','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'cabstar','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'evalia','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'gtr','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'infiniti','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'juke','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'king cab','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'king double cab','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'kubistar','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'leaf','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'maxima','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'micra','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'murano','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'navara','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'note','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'nv200','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'pathfinder','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'patrol','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'pick-up','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'prairie','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'primastar','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'primera','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'qashqai','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'quest ','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'sentra','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'serena','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'sunny','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'terrano','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'tiida','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'tino','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'trade','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'urvan','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'vanette','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'versa','model_date'=>date('Y-m-d'),'brand_id'=>100),
                       array('model_name'=>'x trail','model_date'=>date('Y-m-d'),'brand_id'=>100),

                       array('model_name'=>'100','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'200','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'80','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'90','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a1','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a2','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a3','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a3 berline','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a4','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a4 allroad','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a5 coupe','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a5 SPORTBACK','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a6','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a6 allroad','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a7','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'a8','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'allroad','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'coupe','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'e-tron','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'e-tron  sportback','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'q2','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'q3','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'q3 sportback','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'q5','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'q7','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'q8','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'r8','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'rs q8','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'rs-q3','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'rs2','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'rs3','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'rs4','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'rs5','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'rs6','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'rs7','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'s1','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'s2','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'s3','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'s4','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'s5','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'s6','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'s7','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'s8','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'sq5','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'sq7','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'sq8','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'tt','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'tt-rs','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'tts','model_date'=>date('Y-m-d'),'brand_id'=>2),
                       array('model_name'=>'v8','model_date'=>date('Y-m-d'),'brand_id'=>2),

                       array('model_name'=>'0','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'4runner','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'auris','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'avensis','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'avensisverso','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'aygo','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'c-hr','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'camry','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'carina','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'celica','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'corolla','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'corollacross','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'corollaverso','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'corona','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'cr-h','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'fjcruiser','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'fortuner','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'hiace','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'highlander','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'hilux','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'landcruiser','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'lexus','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'liteace','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'mr','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'paseo','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'picnic','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'prado','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'previa','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'prius','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'rav-4','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'runner','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'sienna','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'starlet','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'supra','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'tercel','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'tundra','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'verso','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'yaris','model_date'=>date('Y-m-d'),'brand_id'=>23),
                       array('model_name'=>'yarisverso','model_date'=>date('Y-m-d'),'brand_id'=>23),

                       array('model_name'=>'3100','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'alero','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'astro','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'avalanche','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'aveo','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'beretta','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'blazer','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'camaro','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'caprice','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'captiva','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'cavalier','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'cmp','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'corvette','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'cr8','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'cruze','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'e400','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'el camino','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'epica','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'evanda','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'express','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'hhr','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'kalos','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'lacetti','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'maruti','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'matiz','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'metro','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'monte-carlo','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'nubira','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'nubira sw','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'optra','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'orlando','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'rezzo','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'s-10','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'silverado','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'spark','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'ssr','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'suburban','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'tacuma','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'tahoe','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'tracker','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'trail blazer','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'trans sport','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'traverse','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'trax','model_date'=>date('Y-m-d'),'brand_id'=>4),
                       array('model_name'=>'uplander','model_date'=>date('Y-m-d'),'brand_id'=>4),


                       array('model_name'=>'accord','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'acty','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'aerodeck','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'city','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'civic','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'concerto','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'cr-v','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'cr-x','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'fr-v','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'hr-v','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'insight','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'integra','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'jazz','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'legend','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'logo','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'nsx','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'odyssey','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'prelude','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'s 2000','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'shuttle','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'stream','model_date'=>date('Y-m-d'),'brand_id'=>7),
                       array('model_name'=>'vigor','model_date'=>date('Y-m-d'),'brand_id'=>7),

                       array('model_name'=>'besta','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'cadenza','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'carens','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'carnival','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'ceed','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'cerato','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'clarus','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'combi','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'k2500','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'k2700','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'k5','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'magentis','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'mohave','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'niro','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'opirus','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'optima','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'picanto','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'pregio','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'pride','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'proceed','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'quoris','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'rio','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'seltos','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'sephia','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'shuma','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'sorento','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'soul','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'sportage','model_date'=>date('Y-m-d'),'brand_id'=>11),
                       array('model_name'=>'stinger','model_date'=>date('Y-m-d'),'brand_id'=>11),

                       array('model_name'=>'dokker','model_date'=>date('Y-m-d'),'brand_id'=>54),
                       array('model_name'=>'duster','model_date'=>date('Y-m-d'),'brand_id'=>54),
                       array('model_name'=>'lodgy','model_date'=>date('Y-m-d'),'brand_id'=>54),
                       array('model_name'=>'logan','model_date'=>date('Y-m-d'),'brand_id'=>54),
                       array('model_name'=>'logan mcv','model_date'=>date('Y-m-d'),'brand_id'=>54),
                       array('model_name'=>'pick-up','model_date'=>date('Y-m-d'),'brand_id'=>54),
                       array('model_name'=>'pick-up double cab','model_date'=>date('Y-m-d'),'brand_id'=>54),
                       array('model_name'=>'sandero','model_date'=>date('Y-m-d'),'brand_id'=>54),
                       array('model_name'=>'solenza','model_date'=>date('Y-m-d'),'brand_id'=>54),

                       array('model_name'=>'2 cv','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'ami','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'ax','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'berlingo','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'bx','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c-crosser','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c-elysee','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c1','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c15','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c2','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c25','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c3','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c3 aircross','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c3 picasso','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c3 pluriel','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c35','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c4','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c4 aircross','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c4 cactus','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c4 picasso','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c4 spacetourer','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c5','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c5 aircross','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c6','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'c8','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'cx','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'ds','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'ds19','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'ds20','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'ds21','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'ds23','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'ds4','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'ds5','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'evasion','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'grand c4 picasso','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'grand c4 spacetourer','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'hy  ','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'jumper','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'jumpy','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'mehari','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'nemo','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'saxo','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'sm','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'spacetourer','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'visa','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'xantia','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'xm','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'xsara','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'xsara picasso','model_date'=>date('Y-m-d'),'brand_id'=>52),
                       array('model_name'=>'zx','model_date'=>date('Y-m-d'),'brand_id'=>52),



                       array('model_name'=>'1007','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'104','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'106','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'107','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'108','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'2008','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'203','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'204','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'205','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'206','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'206 cc','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'206 sw','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'206+','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'207','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'207 cc','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'207 sw','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'208','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'3008','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'301','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'304','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'305','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'306','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'307','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'307 cc','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'307 sw','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'308','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'308 cc','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'308 sw','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'309','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'4007','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'4008','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'403','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'404','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'405','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'406','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'407','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'407 coupe','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'407 sw','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'5008','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'504','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'505','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'508','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'508 rxh','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'604','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'605','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'607','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'806','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'807','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'bipper','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'boxer','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'expert','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'j5','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'j9','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'landtrek','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'partner','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'Partner tepee','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'pick up','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'rcz','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'rifter','model_date'=>date('Y-m-d'),'brand_id'=>17),
                       array('model_name'=>'traveller','model_date'=>date('Y-m-d'),'brand_id'=>17),

                       array('model_name'=>'12','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'14','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'16','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'30','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'avantime','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'b110','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'b120','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'b80','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'captur','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'clio','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'espace','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'estafette','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'express','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'express van','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'fluence','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'fuego','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'grand espace','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'grand modus','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'grand scenic','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'kadjar','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'kangoo','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'koleos','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'LAGUNA ','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'laguna coupe','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'laguna estate','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'latitude','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'mascott','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'master','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'megane','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'megane estate','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'megane sedan','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'messenger','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'microbus','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'modus','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'nevada','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r11','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r18','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r19','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r20','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r21','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r25','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r4','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r5','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r8','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'r9','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'safrane','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'samsung sm3','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'scenic','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'spider','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'super 5','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'symbol','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'talisman','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'trafic','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'twingo','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'twizy','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'vel satis','model_date'=>date('Y-m-d'),'brand_id'=>19),
                       array('model_name'=>'zoe','model_date'=>date('Y-m-d'),'brand_id'=>19),

                       array('model_name'=>'adam','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'agila','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'antara','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'ascona','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'astra','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'calibra','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'campo','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'combo','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'combo cargo','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'combo life','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'corsa','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'crossland ','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'frontera','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'grandland x','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'gt','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'insignia','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'kadett','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'meriva','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'mokka','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'mokka x ','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'monterey','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'movano','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'omega','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'opc','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'rekord','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'signum','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'sintra','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'speedster','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'tigra','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'vectra','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'vivaro','model_date'=>date('Y-m-d'),'brand_id'=>101),
                       array('model_name'=>'zafira','model_date'=>date('Y-m-d'),'brand_id'=>101),

                       array('model_name'=>'b max','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'bedford','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'c max','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'capri','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'connect','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'cougar','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'courrier','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'crown victoria','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'e350','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'ecosport','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'edge','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'escape','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'escort','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'everest','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'excursion','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'expedition','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'explorer','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'f-150','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'f-250','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'f-350','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'fiesta','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'flex','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'focus','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'focus 4P','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'focus c-max','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'fusion','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'galaxy','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'gt','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'ka','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'kuga','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'maverick','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'minibus','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'mondeo','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'mustang','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'orion','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'pick-up','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'probe','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'puma','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'ranger','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'s-max','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'scorpio','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'sierra','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'street ka','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'super duty','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'taunus','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'thunderbird','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'tourneo connect','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'tourneo custom','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'transit','model_date'=>date('Y-m-d'),'brand_id'=>6),
                       array('model_name'=>'victoria','model_date'=>date('Y-m-d'),'brand_id'=>6),


                       array('model_name'=>'accent','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'atos','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'azera','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'centennial','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'county','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'coupe','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'creta','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'elantra','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'equus','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'excel','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'galloper','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'genesis','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'getz','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'grand i10','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'grand santa fe ','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'grandeur','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'h','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'h1','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'h100','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'h200','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'h350','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'i10','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'i20','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'i30','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'i40','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'ioniq','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'ix35','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'ix55','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'kona','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'lantra','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'matrix','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'pony','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'santa fe','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'santamo','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'satellite','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'sonata','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'sonica','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'terracan','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'trajet','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'tucson','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'veloster','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'veracruz','model_date'=>date('Y-m-d'),'brand_id'=>8),
                       array('model_name'=>'xg','model_date'=>date('Y-m-d'),'brand_id'=>8),

                       array('model_name'=>'126','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'127','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'131','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'500','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'500c','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'500l','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'500x','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'850 coupe','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'albea','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'barchetta','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'bertone','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'brava','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'bravo','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'burstner','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'cinquecento','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'coupe','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'croma','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'doblo','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'ducato','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'fiorino','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'freemont','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'fullback','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'grande punto','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'idea','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'linea','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'marea','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'multipla','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'palio','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'panda','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'punto','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'regata','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'ritmo','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'scudo','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'sedici','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'seicento','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'siena','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'stilo','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'talento','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'tempra','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'tipo','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'tipo hatchback','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'toledo','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'ulysse','model_date'=>date('Y-m-d'),'brand_id'=>5),
                       array('model_name'=>'uno','model_date'=>date('Y-m-d'),'brand_id'=>5),

                    );
                       DB::table('car_models')->insert($renault);



    }
}
